#include <SDL3/SDL.h>

#ifndef SDL3_INPUTS_HANDLER_HPP
#define SDL3_INPUTS_HANDLER_HPP

enum class Key
{
    A = SDL_SCANCODE_A,  F1 = SDL_SCANCODE_F1,         NumPad2 = SDL_SCANCODE_KP_2,
    B = SDL_SCANCODE_B,  F2 = SDL_SCANCODE_F2,         NumPad3 = SDL_SCANCODE_KP_3,
    C = SDL_SCANCODE_C,  F3 = SDL_SCANCODE_F3,         NumPad4 = SDL_SCANCODE_KP_4,
    D = SDL_SCANCODE_D,  F4 = SDL_SCANCODE_F4,         NumPad5 = SDL_SCANCODE_KP_5,
    E = SDL_SCANCODE_E,  F5 = SDL_SCANCODE_F5,         NumPad6 = SDL_SCANCODE_KP_6,
    F = SDL_SCANCODE_F,  F6 = SDL_SCANCODE_F6,         NumPad7 = SDL_SCANCODE_KP_7,
    G = SDL_SCANCODE_G,  F7 = SDL_SCANCODE_F7,         NumPad8 = SDL_SCANCODE_KP_8,
    H = SDL_SCANCODE_H,  F8 = SDL_SCANCODE_F8,         NumPad9 = SDL_SCANCODE_KP_9,
    I = SDL_SCANCODE_I,  F9 = SDL_SCANCODE_F9,         NumPadEnter = SDL_SCANCODE_KP_ENTER,
    J = SDL_SCANCODE_J,  F10 = SDL_SCANCODE_F10,
    K = SDL_SCANCODE_K,  F11 = SDL_SCANCODE_F11,       LeftShift = SDL_SCANCODE_LSHIFT,
    L = SDL_SCANCODE_L,  F12 = SDL_SCANCODE_F12,       RightShift = SDL_SCANCODE_RSHIFT,
    M = SDL_SCANCODE_M,                                LeftCtrl = SDL_SCANCODE_LCTRL,
    N = SDL_SCANCODE_N,  Num0 = SDL_SCANCODE_0,        RightCtrl = SDL_SCANCODE_RCTRL,
    O = SDL_SCANCODE_O,  Num1 = SDL_SCANCODE_1,        LeftAlt = SDL_SCANCODE_LALT,
    P = SDL_SCANCODE_P,  Num2 = SDL_SCANCODE_2,        RightAlt = SDL_SCANCODE_RALT,
    Q = SDL_SCANCODE_Q,  Num3 = SDL_SCANCODE_3,        CapsLock = SDL_SCANCODE_CAPSLOCK,
    R = SDL_SCANCODE_R,  Num4 = SDL_SCANCODE_4,        Tab = SDL_SCANCODE_TAB,
    S = SDL_SCANCODE_S,  Num5 = SDL_SCANCODE_5,        Escape = SDL_SCANCODE_ESCAPE,
    T = SDL_SCANCODE_T,  Num6 = SDL_SCANCODE_6,        Backspace = SDL_SCANCODE_BACKSPACE,
    U = SDL_SCANCODE_U,  Num7 = SDL_SCANCODE_7,        Delete = SDL_SCANCODE_DELETE,
    V = SDL_SCANCODE_V,  Num8 = SDL_SCANCODE_8,        Space = SDL_SCANCODE_SPACE,
    W = SDL_SCANCODE_W,  Num9 = SDL_SCANCODE_9,        LeftSuperKey = SDL_SCANCODE_LGUI,
    X = SDL_SCANCODE_X,                                RightSuperKey = SDL_SCANCODE_RGUI,
    Y = SDL_SCANCODE_Y,  NumPad0 = SDL_SCANCODE_KP_0,  Enter = SDL_SCANCODE_RETURN,
    Z = SDL_SCANCODE_Z,  NumPad1 = SDL_SCANCODE_KP_1
};

#endif
